twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
        app_name: '%env(APP_NAME)%'

when@dev:
    twig:
        auto_reload: true

when@test:
    twig:
        strict_variables: true
